// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFeed(arg1:string):Promise<void>;

export function ArticlesForFeed(arg1:string):Promise<Array<main.ArticleViewModel>>;

export function Feeds():Promise<Array<main.FeedViewModel>>;
