// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFeed(arg1) {
  return window['go']['main']['App']['AddFeed'](arg1);
}

export function Feeds() {
  return window['go']['main']['App']['Feeds']();
}
